version: '3.7'

services:
  db_postgres:
    image: postgres:14.1-alpine
    container_name: universitier_db
    environment:
      POSTGRES_DB: universitier
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
        - db_postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - internal

networks:
  internal:

volumes:
  db_postgres: