version: '3.7'

services:
  postgres:
    image: postgres:14.1-alpine
    container_name: universitier_postgres
    environment:
      POSTGRES_DB: universitier
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
        - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - internal

networks:
  internal:

volumes:
  postgres: