spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/universitier
  liquibase:
    contexts: local

logging.level:
  org.springframework.security: DEBUG

app:
  cors: "http://localhost:4200"
