spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/universitier
  liquibase:
    contexts: local

logging.level:
  org.springframework.security: DEBUG

app:
  init: MORE
  cors: "http://localhost:4200"
  jwt:
    expiration-seconds: 3600

